export const GET_LIST_OF_TODOS_REQUEST = "GET_LIST_OF_TODOS_REQUEST";
export const GET_LIST_OF_TODOS_SUCCESS = "GET_LIST_OF_TODOS_SUCCESS";
export const GET_LIST_OF_TODOS_FAILURE = "GET_LIST_OF_TODOS_FAILURE";
export const CREATE_TODO_REQUEST = "CREATE_TODO_REQUEST";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const CREATE_TODO_FAILURE = "CREATE_TODO_FAILURE";
